spring.application.name=ToDo-RESTAPI

# DATASOURCE
spring.datasource.driver-class-name=${DB_DRIVER}
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# DIALECT
spring.jpa.properties.hibernate.dialect=${DB_DIALECT}

# SQL LOGS
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# DLL-AUTO MODE
spring.jpa.hibernate.ddl-auto=update

# LOGGER
logging.level.ru.sddisk.todorestapi=DEBUG